### ISSUE TITLE
Suggestion/Feature Request

### ISSUE THREAD

**Issue by PutNameHere42** [Mrthomas20121-Mods/ThermalExtra#11]
Version: 3.0.1 Minecraft 1.19.2

Sticky Ball seems to have no recipes and isn't oreDictionaried into Slime Balls
Requesting more intigration for sticky balls, since making refined sunflower oil gives you hundreds.

**Comment by Mrthomas20121** [comment]
it used to be part of the tag, guess i removed it and forgot to add it back when i rewrote the mod

**Comment by Mrthomas20121** [comment]
i might add a sticky ball block as well
