### ISSUE TITLE
Blocks can't be mined.

### ISSUE THREAD

**Issue by KodYazanDruid** [Mrthomas20121-Mods/ThermalExtra#12]
Blocks can't be mined with pickaxe (missing minecraft:mineable/pickaxe tag). Even if i add manually they have no loot tables.

**Comment by Mrthomas20121** [comment]
what minecraft and thermal extra version?

**Comment by KodYazanDruid** [comment]
Minecraft version: 1.18.2
Mod version: ThermalExtra 2.0.2
