### ISSUE TITLE
Advanced Filter causes crash.

### ISSUE THREAD

**Issue by KodYazanDruid** [Mrthomas20121-Mods/ThermalExtra#13]
Minecraft: 1.18.2
Forge: 40.1.2
Thermal Extra: 2.0.2
Log: https://gist.github.com/KodYazanDruid/64bcbd6022593e9737b306d16a9063f3

I tried giving advanced filter to vacuumulator and game crashed (right clicking and manually putting)

**Comment by Mrthomas20121** [comment]
i'll look into it
