### ISSUE TITLE
Dragonsteel Integral Component is too weak

### ISSUE THREAD

**Issue by LuciusV** [Mrthomas20121-Mods/ThermalExtra#22]
Please bump it to x6 or make config option to do so, 4.5 is silly: Resonant -> Draconic upgrade only improves speed by miserable 12.5%.
For reference, [this mod](https://www.curseforge.com/minecraft/mc-mods/thermal-endergy) offers x6-x12 upgrade, only reason I dont use that mod is it requires dependency.

**Comment by Mrthomas20121** [comment]
fyi thermal endergy is supposed to be OP, my addon is not. i might do 5 or 5.5/6 but nothing more.

**Comment by LuciusV** [comment]
I updated the mod and it is still 4.5, have it been changed?

**Comment by Mrthomas20121** [comment]
when i did the last update, i forgot to change it so it wasn't changed but i did change it for 1.20.1

**Comment by LuciusV** [comment]
Could you please update it in 1.19.2?
