### ISSUE TITLE
translate problem: “Plate” or "Plating"

### ISSUE THREAD

**Issue by Milk-cake** [Mrthomas20121-Mods/ThermalExtra#23]
Hello!
When I try to translate this mod from en_us to zh_cn,
I found that what I crafted is a DragonBreathPlating but not a "DragonBreathPlate".

Are there any funny cause?

**Comment by Mrthomas20121** [comment]
yeah because it's not a plate. fyi(for your information), only 1.19.2 and 1.20.1 versions of thermal extra are maintained so i won't be adding any translation to the 1.18.2(non overhauled versions as it seems it's what you're using) and the 1.16 version
