### ISSUE TITLE
[Forge 1.20.1] Config file for the mod

### ISSUE THREAD

**Issue by vizthex123** [Mrthomas20121-Mods/ThermalExtra#25]
Would be nice if we could configure the output rate of the Frost Dynamo and stat boosts each augment gives.

KubeJS support for the Frost Dynamo would be great as well.

I also found that the Frost Dynamo's break time is much longer than standard Dynamos.

**Comment by Mrthomas20121** [comment]
no I will not be supporting KubeJS(You may do that yourself with an addon idc)
the break time is the same as the other dynamos(you should be using the wrench anyways)
the config stuff may or may not happen

**Comment by vizthex123** [comment]
Any reason why you won't support KubeJS? What about CraftTweaker?

I just want a way to customize dynamo fuel & whatnot.

**Comment by Mrthomas20121** [comment]
custom dynamo fuel can be done with datapack

**Comment by vizthex123** [comment]
> custom dynamo fuel can be done with datapack

ok, but *how*? What's the folder structure? Is there an example file anywhere?!

not to be rude or anything, but i'm so damn tired of mod devs going "just use a datapack lulz" and giving you 0 direction for wtf you're meant to do with it. At least link to a file and have a line of text listing the folder structure the datapack should use.

**Comment by Mrthomas20121** [comment]
https://github.com/Mrthomas20121-Mods/ThermalExtra/tree/1.20.1/src/main/resources/data/thermal_extra/recipes/machine/dynamo/frost
