### ISSUE TITLE
[3.1.0] Some Augment Upgrades are now worse than their downgrade

### ISSUE THREAD

**Issue by Blackalf** [Mrthomas20121-Mods/ThermalExtra#27]
In the new 3.1.0 version the stats of most augment upgrades has been modified, this comes with a few issues.

The 3 concerned types of augments will be listed below:

Catalytic Reclamation Chamber: Each upgrades increases the Catalyst Usage which contradicts with the point of the upgrade that is to save on catalyst usage

Alchemical Amplifier: Each upgrades decreases the effect duration which of course only makes the potion worse with no added benefits

Flux Linkage Amplifier: Each upgrades increased both the Base Power (BP) and Process Energy (PE), no issues with the BP part but the PE makes the recipes longer (since they require more energy). This not only neglects the added BP effect but since PE is a multiplier stat and BP an additional stat each upgrade of the augment is actually worse.
Here's the calculation of the actual speed boost for each upgrade with 1 and 3 added to a machine:

Speed Boost = (1+ Base Power Modifier)  * (1 * Process Energy Modifier)

1 augment:
T1 = (1 + 1.05) / (1 * 1.05) = 2.05 / 1.05 = x1,95 speed
T2 = (1 + 1.10) / (1 * 1.10) = 2.10 / 1.10 = x1,91 speed
T3 = (1 + 1.15) / (1 * 1.15) = 2.15 / 1.15 = x1,87 speed
T4 = (1 + 1.20) / (1 * 1.20) = 2.20 / 1.20 = x1,83 speed
T5 = (1 + 1.25) / (1 * 1.25) = 2.25 / 1.25 = x1,8 speed

3 augments:
T1 = (1 + 1.05*3) / (1 * 1.05³) = x3.58 speed
T2 = (1 + 1.10*3) / (1 * 1.10³) = x3.23 speed
T3 = (1 + 1.15*3) / (1 * 1.15³) = x2.93 speed
T4 = (1 + 1.20*3) / (1 * 1.20³) = x2.66 speed
T5 = (1 + 1.25*3) / (1 * 1.25³) = x2.43 speed

As we can see, it gets worse and worse the more we add so each upgrade of the Flux Linkage Amplifier should not increase the PE Modifier.

I do want to add that Flux Efficiency augment upgrades are very op as if we do the same calculations we realize that 3 maxed Flux efficiency upgrades gives a x10 speed boost since their PE modifier is very low (0.4x) which makes Flux Linkage Amplifier augments completely useless as they're slower and use more energy.

A fix proposition to make those 2 augments more equitable would be:

Making the Flux Linkage Amplifier upgrades PE modifier to stay at 1.1 like the basic Thermal one and to make each upgrade gives +10% BP than the previous one

Making the Flux Efficiency upgrades Max Power modifier to stay at +10% like the basic Thermal one and to make each upgrade gives -0.05x PE than the previous one instead of the current -0.1x

Only taking in account the maxed augments and using all 3 augment slots in the machinery, the calculations would end up being:

3 FLA:
(1 +1.5*3) / (1 * 1.05³) = x4.75 speed | x1.16 energy consumption

2 FLA 1 FE:
((1 +1.5*2) * (1-0.10)) / (1 * 1.05² * 0.7) = x4.66 speed | x0.77 energy consumption

1 FLA 2FE:
((1 +1.5) * (1-0.10*2)) / (1 * 1.05 * 0.7²) = x3.89 speed | 0.51 energy consumption

3 FE:
(1 * (1-0.10*3)) / (1 * 0.7³) = x2.04 speed | x0.34 energy consumption

Then it is your choice to choose how you want to balance it, I'm just giving ideas :)

Outside of this, thank you for the mod update, it's awesome!

**Comment by Mrthomas20121** [comment]
yeah it's mb, I didn't test the augments properly
