### ISSUE TITLE
Inaccurate fluid ratios

### ISSUE THREAD

**Issue by DerCommander323** [Mrthomas20121-Mods/ThermalExtra#3]
In 1.18(.2?) Tinkers changed the fluid per ingot from 144 to 90 millibuckets, but all the mods recipes still use the 144mb logic, so it doesnt match the rest of tinkers (and the liquid amounts dont properly show as "ingots",etc. in JEI)
![image](https://user-images.githubusercontent.com/80590706/170523611-6e9b98eb-3566-4766-ac57-34a254387c9d.png)
![image](https://user-images.githubusercontent.com/80590706/170523751-dce8823b-fed5-4a44-a42d-d471f60c6488.png)
![image](https://user-images.githubusercontent.com/80590706/170523764-0eab8526-6de0-4e0f-9052-864558ede73c.png)

**Comment by Mrthomas20121** [comment]
known issue, will be fixed soon
