### ISSUE TITLE
Accept any oil in fluid mixer

### ISSUE THREAD

**Issue by albinaask** [Mrthomas20121-Mods/ThermalExtra#37]
Hi! I'm trying to use the fluid mixer to mix flux infused oil, but the oil that spawns in the world happends to be oil from pneumaticcraft. This makes the machine rather unusable. So would it be impossible to exchange the recipe to "#forge:crude_oil" instead, like the fractioning still has?

**Comment by Mrthomas20121** [comment]
that's an oversight on my end, it will be fixed
