### ISSUE TITLE
Suggestion: Component assembly recipes wthout fluid requirement

### ISSUE THREAD

**Issue by Michepoli** [Mrthomas20121-Mods/ThermalExtra#38]
As for now making component assembly custom recipes requires a fluid input and can't be removed for what i know and tried

**Comment by Mrthomas20121** [comment]
i'll look into it

**Comment by Mrthomas20121** [comment]
looking at the code, it should work, can I see what you are trying to do?

**Comment by Michepoli** [comment]
event.custom({	
  "type": "thermal_extra:component_assembly",
  "energy": 100,
  "ingredients": [
    {
      "count": 1,
      "tag": "forge:plates/gold"
    },
    {
      "count": 1,
      "item": 'alltheores:brass_gear'
    },
    {
      "count": 1,
      "item": 'alltheores:electrum_gear'
    },
	{
      "count": 1,
      "item": 'alltheores:constantan_gear'
    },
    {
      "amount": 1,
      "fluid": "minecraft:water"
    }
  ],
  "result": [
    {
      "chance": 1.0,
      "item": "create:precision_mechanism"
    }
  ]
})

this, using only kubejs no kubejs thermal, if i put water amount to 0 it automatically gets set to 1000 in game, without adding the fluid the recipe wouldn't even load (no kubejs errors however)

**Comment by Mrthomas20121** [comment]
why are you putting water?

**Comment by Mrthomas20121** [comment]
i'll test myself and see if I did anything wrong.

**Comment by Mrthomas20121** [comment]
yeah the recipe it works, it just doesn't show up in jei due to a bug in my jei compat, it's fixed now

**Comment by Mrthomas20121** [comment]
oh nvm after checking in game, it doesn't work either

**Comment by Mrthomas20121** [comment]
fixed

**Comment by Michepoli** [comment]
thanks
