### ISSUE TITLE
Fluid Mixer fills both input slots

### ISSUE THREAD

**Issue by RyanP1991** [Mrthomas20121-Mods/ThermalExtra#41]
When using the fluid mixer to make Flux Infused Oil when inputting destablized redstone it fills both slots at the same time so I am unable to add the oil, just wondering am I missing something?

![2024-09-25_20 42 57](https://github.com/user-attachments/assets/c0cd22bf-2d39-4fb4-88c7-057a931d2aaa)

**Comment by Mrthomas20121** [comment]
that's a bug in the gui, are you using the latest version of thermal extra?

**Comment by Mrthomas20121** [comment]
![image](https://github.com/user-attachments/assets/a713e4fa-d7c5-4084-a796-a0e2d5d84d56)
i'm on latest and it works, please update thermal extra.

**Comment by Mrthomas20121** [comment]
if you're playing a modpack, ask the modpack dev to update the mod in the pack.

**Comment by RyanP1991** [comment]
This is on the latest version, I don't think you understand what I am saying, surely the 2 fluid input tanks should be classed as seperate tanks, unless you are requiring both fluids to be inputted at the same rate?

**Comment by biggussalad** [comment]
I am having the same issue. In my situation I have crude oil input from the top of the FM and destabilized redstone input from the bottom. If neither input tank is empty and I am able to input both fluids, there is no issue and each input tank gets its desired input.

The issue occurs when either input source stops and the other continues. When one of the input tanks in the FM empties, it will then get filled by whatever input source is still sending fluid, causing  the tanks to both be filled by one fluid type, and breaking automation.

Ideally both tanks in the FMs gui should be able to be assigned to different input colors in the I/o configuration gui. Just my 2 cents at least.
