### ISSUE TITLE
Weird fluid output in component assembly

### ISSUE THREAD

**Issue by Konhaiii** [Mrthomas20121-Mods/ThermalExtra#46]
When a component assembly recipe has no fluid output, the mod seems to replace it with an "empty" fluid (see screenshot).
When "lookupFluidContentsEnabled" is on in JEI config, it leads to showing theses component assembly recipes as valid recipes for empty containers (like the "watering can" from Thermal Cultivation). On the second screenshot, the watering can is getting linked to the 
redstone servo recipe because they share this "empty" fluid.
![Capture d'écran 2024-10-20 181134](https://github.com/user-attachments/assets/337783dc-5949-4dac-936e-48d64809d3df)
![Capture d'écran 2024-10-20 181149](https://github.com/user-attachments/assets/f952de18-2f9c-4c6a-b249-dea976792cda)
I'm getting this issue in Minecraft 1.20.1, Forge 47.3.0, ThermalExtra 3.1.9b.
I hope I detailed the issue correctly, feel free to ask questions if it is not clear enough.

**Comment by Mrthomas20121** [comment]
I mean that's not really a bug, just how I do it but I have fixed it for a future update
