### ISSUE TITLE
BUG: Component assembly recipes can use the wrong number of items.

### ISSUE THREAD

**Issue by Michepoli** [Mrthomas20121-Mods/ThermalExtra#47]
Using latest version of the mod and latest version of forge in 1.20.1.
![immagine](https://github.com/user-attachments/assets/5d818803-514b-4d51-8a43-325fbea51dc5)
This is the recipe shown in jei.
![immagine](https://github.com/user-attachments/assets/eb1ac2a0-2fce-4b12-8142-44cb637d2a98)
And this is how the items are placed inside the assembly, it expects at least another circuit board (the item in the top right) to start the recipe cause it's using the count of the vaccum tubes (the item at the bottom left).
The wrong item counts are used if items are placed differently from the json.

**Comment by Michepoli** [comment]
![immagine](https://github.com/user-attachments/assets/bafa05c1-3bb3-4f7d-95fb-27680f244b21)
item is stackable btw

**Comment by Mrthomas20121** [comment]
i'll look into it

**Comment by Mrthomas20121** [comment]
just to confirm, does this happens on the latest update of the mod?

**Comment by Michepoli** [comment]
no but now the items have to be placed exactly how they are in jei for the recipe to start and can be a bit annoying

**Comment by Mrthomas20121** [comment]
that is indeed the case. I don't see any other way to fix this for now
