### ISSUE TITLE
Sticky ball

### ISSUE THREAD

**Issue by Samjjjjjjj** [Mrthomas20121-Mods/ThermalExtra#49]
There is a way to craft "sticky ball"? In the modpack i'm playing there is no info about it and the jei only shows crafting recipes that requires stickies ball but not how to craft them.

**Comment by Mrthomas20121** [comment]
mc version?

**Comment by Samjjjjjjj** [comment]
1.20.1

**Comment by Mrthomas20121** [comment]
I found the issue, it's a broken recipe
