### ISSUE TITLE
not working on 1.16.5

### ISSUE THREAD

**Issue by RobinErza** [Mrthomas20121-Mods/ThermalExtra#5]
i want use ur mods for my modspack i got error version

**Comment by Mrthomas20121** [comment]
i can't help you without logs and/or crash reports.

**Comment by RobinErza** [comment]
net.minecraftforge.fml.ModLoadingException: Mod ethermal_extrar requires  cofh_corer obetween 1.4.1 and 1.5 (inclusive)
Currently, cofh_corer is 1.5.2.22 here the error

**Comment by RobinErza** [comment]
pls can you update the mods i want really use ur mods
