### ISSUE TITLE
Thermal Extra Hardened Glass variants can´t be created using Induction Smelter

### ISSUE THREAD

**Issue by diefesson** [Mrthomas20121-Mods/ThermalExtra#50]
Minecraft version: `1.20.1`
Thermal Extra version: `3.1.9b`

Thermal hardened glass variants can be crafted using both the crafting table and the induction smelter

![Captura de tela 2024-11-06 151028](https://github.com/user-attachments/assets/3f4c956f-3f54-440e-9135-271f32392fbe)

![Captura de tela 2024-11-06 151038](https://github.com/user-attachments/assets/42d0dbf7-bc85-4b5e-9791-b992bcabd0d8)

But Thermal Extra variants can only be crafted using the crafiting table

![Captura de tela 2024-11-06 151050](https://github.com/user-attachments/assets/3edd128b-8a91-4700-9335-98e2a9d08688)

Already verified it's not just a recipe viewer problem

**Comment by Mrthomas20121** [comment]
I moved recipes to datagen and forgot to add it back mb
