### ISSUE TITLE
Alchemical Inbuer not accepting Amethyst Shards 

### ISSUE THREAD

**Issue by mikes4b22** [Mrthomas20121-Mods/ThermalExtra#54]
The Alchemical Inbuer is not accepting Amethyst Shards as an input but is successfully filling with Sunflower Oil. Can't continue with Refined SO without it. Simple fix or am I missing something?
Version: ThermalExtra-3.2.1-1.20.1

**Comment by Mrthomas20121** [comment]
it works for me

**Comment by mikes4b22** [comment]
I got it to work now too, not sure what was wrong but all is well in the end.
