### ISSUE TITLE
Possibly wrong recipes for soul-infused augments

### ISSUE THREAD

**Issue by pics2299** [Mrthomas20121-Mods/ThermalExtra#6]
The soul-infused augments seem to require netherite and dragonsteel gears, just as the last tier of augments. I was wondering if instead, the soul-infused gears were meant to be used in the recipe, as they are left with no use. I'm playing version 3.0.0 btw.

**Comment by Mrthomas20121** [comment]
i see, this will be fixed

**Comment by Mrthomas20121** [comment]
a fix for 1.19.2 and 1.18.2 has been published to curseforge
