### ISSUE TITLE
Polarium recipe doesn't work in MC 1.16.5 mod-v.1.0.5

### ISSUE THREAD

**Issue by MeiNanita** [Mrthomas20121-Mods/ThermalExtra#8]
As stated in the title, I've tried to get some polarium via the induction smelter, however the polarium recipe only shows the usage of a singular lead-dust (and nothing else) which, if I insert it into the induction smelter, only generated a lead ingot.

I'm currently using minecraft version 1.16.5 due to a modpack I'm playing and the mod-version I'm using is 1.0.5, aka the latest 1.16.5 mod-version.
If this issue could be retroactively solved for the 1.16.5 version as well, I would be very happy about it!

**Comment by Mrthomas20121** [comment]
i know it doesn't work. i fixed it in 1.18.2 but didn't change it in 1.16.5
